cfp/urls.py
from django.urls import path, re_path, register_converter, include

from . import views, converters


register_converter(converters.SignedIntConverter, 'sint')


urlpatterns = [
    path('', views.home, name='home'),
    path('cfp/', views.proposal_home, name='proposal-home'),
    path('cfp/token/', views.proposal_mail_token, name='proposal-mail-token'),
    re_path(r'^cfp/(?:(?P<speaker_token>[\w\-]+)/)?dashboard/$', views.proposal_dashboard, name='proposal-dashboard'),
    re_path(r'^cfp/(?:(?P<speaker_token>[\w\-]+)/)?profile/$', views.proposal_speaker_edit, name='proposal-profile-edit'),
    re_path(r'^cfp/(?:(?P<speaker_token>[\w\-]+)/)?talk/add/$', views.proposal_talk_edit, name='proposal-talk-add'),
    re_path(r'^cfp/(?:(?P<speaker_token>[\w\-]+)/)?talk/(?P<talk_id>[0-9]+)/$', views.proposal_talk_details, name='proposal-talk-details'),
    re_path(r'^cfp/(?:(?P<speaker_token>[\w\-]+)/)?talk/(?P<talk_id>[0-9]+)/edit/$', views.proposal_talk_edit, name='proposal-talk-edit'),
    re_path(r'^cfp/(?:(?P<speaker_token>[\w\-]+)/)?talk/(?P<talk_id>[0-9]+)/speaker/add/$', views.proposal_speaker_edit, name='proposal-speaker-add'),
    re_path(r'^cfp/(?:(?P<speaker_token>[\w\-]+)/)?talk/(?P<talk_id>[0-9]+)/speaker/add/(?P<speaker_id>[0-9]+)/$', views.proposal_speaker_add, name='proposal-speaker-add-existing'),
    #re_path(r'^cfp(?:/(?P<speaker_token>[\w\-]+))?/talk/(?P<talk_id>[0-9]+)/speaker/(?P<co_speaker_id>[0-9]+)/$', views.proposal_speaker_details, name='proposal-speaker-details'),
    re_path(r'^cfp/(?:(?P<speaker_token>[\w\-]+)/)?talk/(?P<talk_id>[0-9]+)/speaker/(?P<co_speaker_id>[0-9]+)/edit/$', views.proposal_speaker_edit, name='proposal-speaker-edit'),
    re_path(r'^cfp/(?:(?P<speaker_token>[\w\-]+)/)?talk/(?P<talk_id>[0-9]+)/speaker/(?P<co_speaker_id>[0-9]+)/remove/$', views.proposal_speaker_remove, name='proposal-speaker-remove'),
    re_path(r'^cfp/(?:(?P<speaker_token>[\w\-]+)/)?talk/(?P<talk_id>[0-9]+)/confirm/$', views.proposal_talk_acknowledgment, {'confirm': True}, name='proposal-talk-confirm'),
    re_path(r'^cfp/(?:(?P<speaker_token>[\w\-]+)/)?talk/(?P<talk_id>[0-9]+)/desist/$', views.proposal_talk_acknowledgment, {'confirm': False}, name='proposal-talk-desist'),
    path('volunteer/enrole', views.volunteer_enrole, name='volunteer-enrole'),
    path('volunteer/token/', views.volunteer_mail_token, name='volunteer-mail-token'),
    re_path(r'^volunteer/(?:(?P<volunteer_token>[\w\-]+)/)?$', views.volunteer_dashboard, name='volunteer-dashboard'),
    re_path(r'^volunteer/(?:(?P<volunteer_token>[\w\-]+)/)?profile/$', views.volunteer_profile, name='volunteer-profile-edit'),
    re_path(r'^volunteer/(?:(?P<volunteer_token>[\w\-]+)/)?join/(?P<activity>[\w\-]+)/$', views.volunteer_update_activity, {'join': True}, name='volunteer-join'),
    re_path(r'^volunteer/(?:(?P<volunteer_token>[\w\-]+)/)?quit/(?P<activity>[\w\-]+)/$', views.volunteer_update_activity, {'join': False}, name='volunteer-quit'),
    path('staff/', views.staff, name='staff'),
    path('staff/talks/', views.talk_list, name='talk-list'),
    path('staff/talks/<int:talk_id>/', views.talk_details, name='talk-details'),
    path('staff/talks/<int:talk_id>/vote/<sint:score>/', views.talk_vote, name='talk-vote'),
    path('staff/talks/<int:talk_id>/accept/', views.talk_decide, {'accept': True}, name='talk-accept'),
    path('staff/talks/<int:talk_id>/decline/', views.talk_decide, {'accept': False}, name='talk-decline'),
    path('staff/talks/<int:talk_id>/confirm/', views.talk_acknowledgment, {'confirm': True}, name='talk-confirm-by-staff'),
    path('staff/talks/<int:talk_id>/desist/', views.talk_acknowledgment, {'confirm': False}, name='talk-desist-by-staff'),
    path('staff/talks/<int:talk_id>/edit/', views.TalkUpdate.as_view(), name='talk-edit'),
    path('staff/talks/email/', views.talk_email, name='talk-email'),
    path('staff/talks/email/preview/', views.talk_email_preview, name='talk-email-preview'),
    path('staff/speakers/', views.participant_list, name='participant-list'),
    path('staff/speakers/add/', views.ParticipantCreate.as_view(), name='participant-add'),
    path('staff/speakers/<int:participant_id>/', views.participant_details, name='participant-details'),
    path('staff/speakers/<int:participant_id>/add-talk/', views.participant_add_talk, name='participant-add-talk'),
    path('staff/speakers/<int:participant_id>/edit/', views.ParticipantUpdate.as_view(), name='participant-edit'),
    path('staff/speakers/<int:participant_id>/remove/', views.ParticipantRemove.as_view(), name='participant-remove'),
    path('staff/speakers/email/', views.speaker_email, name='speaker-email'),
    path('staff/speakers/email/preview/', views.speaker_email_preview, name='speaker-email-preview'),
    path('staff/tracks/', views.TrackList.as_view(), name='track-list'),
    path('staff/tracks/add/', views.TrackCreate.as_view(), name='track-add'),
    path('staff/tracks/<slug:slug>/edit/', views.TrackUpdate.as_view(), name='track-edit'),
    path('staff/rooms/', views.RoomList.as_view(), name='room-list'),
    path('staff/rooms/add/', views.RoomCreate.as_view(), name='room-add'),
    path('staff/rooms/<slug:slug>/', views.RoomDetail.as_view(), name='room-details'),
    path('staff/rooms/<slug:slug>/edit/', views.RoomUpdate.as_view(), name='room-edit'),
    path('staff/volunteers/', views.volunteer_list, name='volunteer-list'),
    path('staff/volunteers/<int:volunteer_id>/', views.volunteer_details, name='volunteer-details'),
    path('staff/volunteers/email/', views.volunteer_email, name='volunteer-email'),
    path('staff/volunteers/email/preview/', views.volunteer_email_preview, name='volunteer-email-preview'),
    path('staff/add-user/', views.create_user, name='create-user'),
    re_path(r'^staff/schedule/((?P<program_format>[\w]+)/)?$', views.staff_schedule, name='staff-schedule'),
    path('staff/select2/', include('django_select2.urls')),
    path('admin/', views.admin, name='admin'),
    path('admin/conference/', views.conference_edit, name='conference-edit'),
    path('admin/homepage/', views.homepage_edit, name='homepage-edit'),
    path('admin/categories/', views.TalkCategoryList.as_view(), name='category-list'),
    path('admin/categories/add/', views.TalkCategoryCreate.as_view(), name='category-add'),
    path('admin/categories/<int:pk>/edit/', views.TalkCategoryUpdate.as_view(), name='category-edit'),
    path('admin/tags/', views.TagList.as_view(), name='tag-list'),
    path('admin/tags/add/', views.TagCreate.as_view(), name='tag-add'),
    path('admin/tags/<slug:slug>/edit/', views.TagUpdate.as_view(), name='tag-edit'),
    path('admin/activities/', views.ActivityList.as_view(), name='activity-list'),
    path('admin/activities/add/', views.ActivityCreate.as_view(), name='activity-add'),
    path('admin/activities/<slug:slug>/edit/', views.ActivityUpdate.as_view(), name='activity-edit'),
    path('admin/evict/', views.schedule_evict, name='schedule-evict'),
    re_path(r'^schedule/((?P<program_format>[\w]+)/)?$', views.public_schedule, name='public-schedule'),
]

ponyconf/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings

from . import views


urlpatterns = [
    path('markdown/', views.markdown_preview, name='markdown-preview'),
    path('admin/django/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('cfp.urls')),
]

if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

mailing/models.py
from django.db import models
from django.utils.crypto import get_random_string
from django.core.mail import EmailMessage, get_connection
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

import hashlib


def generate_message_token():
    # /!\ birthday problem
    return get_random_string(length=32, allowed_chars='abcdefghijklmnopqrstuvwxyz0123456789')


def hexdigest_sha256(*args):
    r = hashlib.sha256()
    for arg in args:
        r.update(str(arg).encode('utf-8'))
    return r.hexdigest()


class MessageCorrespondent(models.Model):
    email = models.EmailField()
    token = models.CharField(max_length=64, default=generate_message_token, unique=True)


class MessageAuthor(models.Model):
    author_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, blank=True)
    author_id = models.PositiveIntegerField(null=True, blank=True)
    author = GenericForeignKey('author_type', 'author_id')
    token = models.CharField(max_length=64, default=generate_message_token, unique=True)

    def __str__(self):
        author_class = self.author_type.model_class()
        if self.author is not None and author_class == get_user_model():
            return self.author.get_full_name()
        else:
            return str(self.author)


class MessageThread(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    token = models.CharField(max_length=64, default=generate_message_token, unique=True)


class MessageManager(models.Manager):
    def get_queyset(self):
        qs = super().get_queryset()
        # Does not work so well as prefetch_related is limited to one content type for generic foreign keys
        qs = qs.prefetch_related('author__author')
        return qs


class Message(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    thread = models.ForeignKey(MessageThread, on_delete=models.CASCADE)
    author = models.ForeignKey(MessageAuthor, on_delete=models.PROTECT)
    in_reply_to = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL)
    subject = models.CharField(max_length=1000, blank=True)
    content = models.TextField(blank=True)
    token = models.CharField(max_length=64, default=generate_message_token, unique=True)

    objects = MessageManager()

    class Meta:
        ordering = ['created']

    def send_notification(self, sender, dests, reply_to=None, message_id=None, reference=None, footer=None, subject=None):
        messages = []
        for dest, dest_name, dest_email in dests:
            dest_type = ContentType.objects.get_for_model(dest)
            dest, _ = MessageAuthor.objects.get_or_create(author_type=dest_type, author_id=dest.pk)
            token = self.token + dest.token + hexdigest_sha256(settings.SECRET_KEY, self.token, dest.token)[:16]
            if reply_to:
                reply_to_name, reply_to_email = reply_to
                reply_to_list = ['%s <%s>' % (reply_to_name, reply_to_email.format(token=token))]
            else:
                reply_to_list = []
            headers = dict()
            if message_id:
                headers.update({
                    'Message-ID': message_id.format(id=self.token),
                })
            if message_id and reference:
                headers.update({
                    'References': message_id.format(id=reference),
                })
            body = self.content
            if footer is not None:
                body += footer
            messages.append(EmailMessage(
                subject=subject or self.subject,
                body=body,
                from_email='%s <%s>' % sender,
                to=['%s <%s>' % (dest_name, dest_email)],
                reply_to=reply_to_list,
                headers=headers,
            ))
        connection = get_connection()
        connection.send_messages(messages)

    def __str__(self):
        return _("Message from %(author)s") % {'author': str(self.author)}

cfp/templates/cfp/staff/participant_details.html
{% extends 'cfp/staff/base.html' %}
{% load i18n %}

{% block title %}{{ participant.name }} - {{ conference.name }}{% endblock %}

{% block speakerstab %} class="active"{% endblock %}

{% block content %}

<h1>
    {{ participant }}
    {% if participant.vip %}<span class="badge">{% trans "VIP" %}</span>{% endif %}
</h1>

<p>
<a class="btn btn-success" href="{% url 'participant-edit' participant.pk %}">{% trans "Edit" %}</a>
{% if not participant.talk_set.exists %} -
<a class="btn btn-danger" href="{% url 'participant-remove' participant.pk %}" >{% trans "Remove" %}</a>
{% endif %}
</p>

<h2>{% trans "Biography" %}</h2>
<p>{{ participant.biography|linebreaksbr }}</p>

{% if participant.notes %}
<h2>{% trans "Notes" %}</h2>
<p>{{ participant.notes|linebreaksbr }}</p>
{% endif %}

<h2>{% trans "Information" %}</h2>
<ul>
    {% if participant.vip %}<li><b>{% trans "Invited speaker" %}</b></li>{% endif %}
    <li><b>{% trans "E-mail:" %}</b> <a href="mailto:{{ participant.email }}">{{ participant.email }}</a></li>
    {% if participant.twitter %}<li><b>{% trans "Twitter:" %}</b> <a href="{{ participant.twitter }}">{{ participant.twitter }}</a></li>{% endif %}
    {% if participant.linkedin %}<li><b>{% trans "LinkedIn:" %}</b> <a href="{{ participant.linkedin }}">{{ participant.linkedin }}</a></li>{% endif %}
    {% if participant.github %}<li><b>{% trans "Github:" %}</b> <a href="{{ participant.github }}">{{ participant.github }}</a></li>{% endif %}
    {% if participant.website %}<li><b>{% trans "Website:" %}</b> <a href="{{ participant.website }}">{{ participant.website }}</a></li>{% endif %}
    {% if participant.facebook %}<li><b>{% trans "Facebook:" %}</b> <a href="{{ participant.facebook }}">{{ participant.facebook }}</a></li>{% endif %}
    {% if participant.mastodon %}<li><b>{% trans "Mastodon:" %}</b> <a href="{{ participant.mastodon }}">{{ participant.mastodon }}</a></li>{% endif %}
    {% if participant.phone_number %}<li><b>{% trans "Phone number:" %}</b> {{ participant.phone_number }}</li>{% endif %}
    {% if participant.language %}<li><b>{% trans "Language:" %}</b> {{ participant.language }}</li>{% endif %}
    <li><b>{% trans "Secret link:" %}</b> <a href="{{ participant.get_secret_url }}">{{ participant.token }}</a></li>
</ul>

<h2>{% trans "Talks" %}</h2>
{% regroup participant.talk_set.all by category as category_list %}
{% for category in category_list %}
<h3>{{ category.list.0.category }}</h3>
<ul>{% for talk in category.list %}
  <li>
    <a href="{% url 'talk-details' talk.pk %}">{{ talk }}</a>
    <i>{% trans "by" %}</i>
    {% for p in talk.speakers.all %}
    {% if p == participant %}{{ p }}{% else %}<a href="{% url 'participant-details' p.pk %}">{{ p }}</a>{% endif %}
    {% if forloop.revcounter == 2 %} {% trans "and" %} {% elif not forloop.last %}, {% endif %}
    {% endfor %}
    {% if talk.track %}
    <i>{% trans "in" %}</i>
    {{ talk.track }}
    {% endif %}
    <span class="label label-{{ talk.get_status_color }}">{{ talk.get_status_str }}</span>
  </li>
  {% endfor %}
</ul>
{% empty %}
<p>{% trans "No talks" %}</p>
{% endfor %}
<p>
  <a class="btn btn-success" href="{% url 'participant-add-talk' participant.pk %}">{% trans "Add a talk" %}</a>
</p>

<h2>{% trans "Messaging" %}</h2>

{% include 'mailing/_message_list.html' with messages=participant.conversation.message_set.all %}

{% trans "Send a message – <em>this message will be received by this participant and all the staff team</em>" as message_form_title %}
{% include 'mailing/_message_form.html' %}

{% endblock %}

cfp/templates/cfp/staff/speaker_email.html
{% extends 'cfp/staff/base.html' %}
{% load i18n bootstrap3 static %}

{% block speakerstab %} class="active"{% endblock %}

{% block content %}

<div class="page-header">
  <h1>{% trans "Send an email to each speaker" %}</h1>
</div>

<form method="POST">
{% csrf_token %}

<h4>{% trans "Please write your email bellow:" %}</h4>

<p>
  {% blocktrans %}You can use <a href="http://jinja.pocoo.org/docs/2.10/">Jinja2</a> templating language.{% endblocktrans %}
  {% blocktrans %}To see available environment variables, please click on a speaker.{% endblocktrans %}
</p>

<div class="row">
  <div class="col-md-12">
    {% bootstrap_form form exclude='confirm' %}
  </div>
</div>

<h4>{% trans "To preview your email, click on a speaker:" %}</h4>

<div class="row">
  <div class="col-md-12">
    <a href="preview"></a>
    <pre id="preview" class="hidden"></pre>
  </div>
  <div class="col-md-12">
    <ul class="list-group">
      {% for speaker in speakers.all %}
      <a class="list-group-item" onclick="preview({{ speaker.pk }});">
        <b>{{ speaker }}</b>
      </a>
      {% endfor %}
    </ul>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    {% if form.confirm %}
    {% bootstrap_field form.confirm %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">{% trans "Send!" %}</button>
    {% endbuttons %}
    {% else %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">{% trans "Check template validity" %}</button>
    {% endbuttons %}
    {% endif %}
  </div>
</div>

</form>

{% endblock %}

{% block js_end %}
{{ block.super }}
{{ form.media.js }}
<script src="{% static 'jquery.cookie/jquery.cookie.js' %}"></script>
<script type="text/javascript">
var csrftoken = $.cookie('csrftoken');
var preview_url = "{% url 'speaker-email-preview' %}";

function csrfSafeMethod(method) {
  // these HTTP methods do not require CSRF protection
  return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}

$.ajaxSetup({
  beforeSend: function(xhr, settings) {
    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
      xhr.setRequestHeader("X-CSRFToken", csrftoken);
    }
  }
});

function preview(speaker) {
    $('#preview').removeClass('hidden');
    $('#preview').html('Loading preview...');
    var body = $('#body').val();
    $.post(preview_url, {
            'speaker': speaker,
            'subject': $('#id_subject').val(),
            'body': $('#id_body').val(),
        })
        .done(function(data, textStatus) {
            $('#preview').html(data);
        })
        .fail(function () {
            $('#preview').html('Sorry, an error occured.');
        })
        .always(function () {
            $(document).scrollTop($('#preview').offset().top);
        });
}
</script>
{% endblock %}

{% block css %}
{{ block.super }}
{{ form.media.css }}
{% endblock %}

cfp/templates/cfp/staff/talk_details.html
{% extends 'cfp/staff/base.html' %}
{% load bootstrap3 i18n %}

{% block talkstab %} class="active"{% endblock %}

{% block content %}

<h1>{{ talk.title }}</h1>

<p><a class="btn btn-success" href="{% url 'talk-edit' talk.pk %}">{% trans "Edit" %}</a></p>

<h3>{% trans "Information" %}</h3>

<dl class="dl-horizontal">
    <dt>{% trans "Category" %}</dt>
      <dd><a href="{{ talk.category.get_absolute_url }}">{{ talk.category }}</a></dd>

    <dt>{% trans "Status" %}</dt>
      <dd><span class="label label-{{ talk.get_status_color }}">{{ talk.get_status_str }}</span></dd>

    <dt>{% trans "Track" %}</dt>
      <dd>{% if talk.track %}
        <a href="{{ talk.track.get_absolute_url }}">{{ talk.track }}</a>
      {% else %}
      <em>{% trans "not defined" context "session" %}</em>
      {% endif %}</dd>

    <dt>{% trans "Tags" %}</dt>
      <dd>{% if talk.tags.exists %}{{ talk.get_tags_html }}{% else %}<em>{% trans "none" context "tag" %}</em>{% endif %}</dd>

    <dt>{% trans "Timeslot" %}</dt>
      <dd>{% if talk.start_date %}
          <span class="date">{{ talk.start_date|date:"l d b" }}</span>,
          <span class="time">{{ talk.start_date|date:"H:i" }} &ndash; {% if talk.end_date %}{{ talk.end_date|date:"H:i" }}{% else %}?{% endif %}</span>
          {% else %}<em>{% trans "not defined" %}</em>
          {% endif %}
      </dd>
    <dt>{% trans "Room" %}</dt>
      <dd>{% if talk.room %}
        <a href="{{ talk.room.get_absolute_url }}">
          <span class="label label-info">{{ talk.room }}</span>
        </a>
        {% else %}<em>{% trans "not defined" %}</em>
        {% endif %}
      </dd>
    {% comment %}
    {% if talk.registration_required %}
    <dt>{% trans "Registrations" %}</dt>
      <dd>{% if talk.attendees_limit %}{{ talk.attendees.count }} / {{ talk.attendees_limit }}{% else %}{% trans "required but unlimited" %}{% endif %}</dd>
    {% endif %
    {% endcomment %}
    {% if talk.materials %}
    <dt>{% trans "Materials" %}</dt>
      <dd><a href="{{ talk.materials.url }}">{{ talk.materials_name }}</a></dd>
    {% endif %}
    {% if talk.video %}
    <dt>{% trans "Video" %}</dt>
      <dd><a href="{{ talk.video }}">{% trans "download" %}</a></dd>
    {% endif %}

</dl>

<h3>{% trans "Description" %}</h3>

<p>{% if talk.description %}{{ talk.description|linebreaksbr }}{% else %}<i>{% trans "No description provided." %}</i>{% endif %}</p>

<h3>{% trans "Speakers" %}</h3>

{% for participant in talk.speakers.all %}
{% if forloop.first %}<ul>{% endif %}
    <li>
      <a href="{% url 'participant-details' participant.pk %}">{{ participant }}</a>
      {% if participant.vip %} <span class="badge">VIP</span>{% endif %}
    </li>
{% if forloop.last %}</ul>{% endif %}
{% empty %}
<i>{% trans "No speakers." %}</i>
{% endfor %}

<br />

<h3>{% trans "Notes" %}</h3>

<p>{% if talk.notes %}{{ talk.notes|linebreaksbr }}{% else %}<i>{% trans "No notes." %}</i>{% endif %}</p>

{% if talk.accepted == None %}
<h3>{% trans "Vote" %}</h3>

<p>
<div class="btn-group" role="group" aria-label="vote">
  <a class="btn {% if vote == -2 %} active {% endif %}btn-danger"  href="{% url 'talk-vote' talk.pk -2 %}">-2</a>
  <a class="btn {% if vote == -1 %} active {% endif %}btn-warning" href="{% url 'talk-vote' talk.pk -1 %}">-1</a>
  <a class="btn {% if vote == 0 %}  active {% endif %}btn-default" href="{% url 'talk-vote' talk.pk  0  %}"> 0</a>
  <a class="btn {% if vote == 1 %}  active {% endif %}btn-info"    href="{% url 'talk-vote' talk.pk  1  %}">+1</a>
  <a class="btn {% if vote == 2 %}  active {% endif %}btn-success" href="{% url 'talk-vote' talk.pk  2  %}">+2</a>
</div>
</p>

<p><button class="btn btn-info" onclick="toggle_votes()">{% trans "Toggle actual votes" %}</button> <span id="actual_votes" class="invisible">{{ talk.vote_set.count }} {% trans "vote" %}{{ talk.vote_set.count|pluralize }}, {% trans "average:" %} {{ talk.score|floatformat:1 }}</span></p>
<script>
function toggle_votes(){
  let votes = document.getElementById('actual_votes');
  if (votes != null) {
    if (votes.className == "invisible") {
      votes.className = "visible";
    } else {
      votes.className = "invisible";
    }
  }
}
</script>

<a href="{% url 'talk-accept' talk.pk %}" class="btn btn-success">{% trans "Accept" %}</a>
<a href="{% url 'talk-decline' talk.pk %}" class="btn btn-danger">{% trans "Decline" %}</a>
{% elif talk.accepted == True and talk.confirmed == None %}
<h3>{% trans "Speaker confirmation" %}</h3>

<a href="{% url 'talk-confirm-by-staff' talk.pk %}" class="btn btn-success">{% trans "The speaker confirmed" %}</a>
<a href="{% url 'talk-desist-by-staff' talk.pk %}" class="btn btn-danger">{% trans "The speaker cancelled" %}</a>
{% endif %}

{% comment %}
{% if talk.registration_required %}
<h3>{% trans "Attendees" %}</h3>

{% for attendee in talk.attendees.all %}
{% if forloop.first %}<ol>{% endif %}
  <li><a href="mailto:{{ attendee.get_email }}">{{ attendee.get_name }}</a></li>
{% if forloop.last %}</ol>{% endif %}
{% empty %}
<em>{% trans "No attendees yet." %}</em>
{% endfor %}

{% endif %}
{% endcomment %}

<h3>{% trans "Messaging" %}</h3>

{% include 'mailing/_message_list.html' with messages=talk.conversation.message_set.all %}

{% trans "Comment this talk – <em>this message will be received by the staff team only</em>" as message_form_title %}
{% include 'mailing/_message_form.html' %}

{% endblock %}

cfp/templates/cfp/staff/volunteer_details.html
{% extends 'cfp/staff/base.html' %}
{% load bootstrap3 i18n %}

{% block volunteersstafftab %} class="active"{% endblock %}

{% block content %}

<h1>{% trans "Volunteer" %} <b>{{ volunteer.name }}</b></h1>

<dl class="dl-horizontal">
  <dt>{% trans "Email:" %}</dt>
    <dd><a href="mailto:{{ volunteer.email }}">{{ volunteer.email }}</a></dd>
  {% if volunteer.phone_number %}
  <dt>{% trans "Phone number:" %}</dt>
    <dd><a href="tel:{{ volunteer.phone_number }}">{{ volunteer.phone_number }}</a>{% if volunteer.sms_prefered %} (SMS){% endif %}</dd>
  {% endif %}
  <dt>{% trans "Secret link:" %}</dt>
    <dd><a href="{{ volunteer.get_secret_url }}">{{ volunteer.token }}</a></dd>
</dl>

{% if volunteer.notes %}
<h3>{% trans "Notes" %}</h3>

<p>{{ volunteer.notes|linebreaksbr }}</p>
{% endif %}

<h3>{% trans "Activities" %}</h3>

{% for activity in volunteer.activities.all %}
{% if forloop.first %}
{% trans "This volunteer applied for the following activities:" %}
<ul>
{% endif %}
    <li>
        {{ activity.name }}
    </li>
{% if forloop.last %}
</ul>
{% endif %}
{% empty %}
{% trans "This volunteer hasn't applied for any activities." %}
{% endfor %}


<h2>{% trans "Messaging" %}</h2>

{% include 'mailing/_message_list.html' with messages=volunteer.conversation.message_set.all %}

{% trans "Send a message" as message_form_title %}
{% include 'mailing/_message_form.html' %}

{% endblock %}